name: 'update-release-action'
description: 'Updates a Release'

inputs:
  github_token:
    description: 'GitHub token or secret'
    required: true
  release_name:
    description: 'Name of the release'
    required: false
  file:
    description: 'File or Pattern of files to upload'
    required: false
  asset_name:
    description: 'Name of the file'
    required: false
  is_file_glob:
    description: 'Is File a pattern'
    required: false
  overwrite:
    description: 'Whether or not to overwrite existing files in the release'
    required: false
  release_notes:
    description: 'Notes to add to the release'
    required: false
  deletes_existing_release:
    description: 'Deletes existing release'
    required: false
  pre_release:
    description: 'Pre-Release'
    required: false
  owner:
    description: 'Repository Owner'
    required: false
  repo:
    description: 'Repository Name'
    required: false
  tag:
    description: 'Commit hash or tag'
    required: true
  ref:
    description: 'Commit hash or tag'
    required: false

outputs:
  result: 
    description: 'JSON array of check-run information [{"id": 1234, "name": "build", "status": "completed|failed", "conclusion": "success|failure"}].'

runs:
  using: 'node12'
  main: 'src/index.js'
